// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message for requesting list of cloud locations..
public struct ListCloudLocationsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent, which owns this collection of cloud locations.
  /// Format: projects/{project}/locations/{location}
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of cloud locations to return per page. The
  /// service might return fewer cloud locations than this value. If unspecified,
  /// server will pick an appropriate default.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token identifying a page of results the server should return.
  /// Provide page token returned by a previous 'ListCloudLocations' call to
  /// retrieve the next page of results. When paginating, all other parameters
  /// provided to 'ListCloudLocations' must match the call that provided the page
  /// token.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. A filter expression that filters resources listed in the
  /// response. The expression is in the form of field=value. For example,
  /// 'cloud_location_type=CLOUD_LOCATION_TYPE_REGION'. Multiple filter queries
  /// are space-separated. For example,
  /// 'cloud_location_type=CLOUD_LOCATION_TYPE_REGION territory_code="US"' By
  /// default, each expression is an AND expression. However, you can include AND
  /// and OR expressions explicitly.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListCloudLocationsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCloudLocationsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.locationfinder.v1.ListCloudLocationsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
